# Generated by Django 2.2.10 on 2020-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(default='', max_length=20, verbose_name='provider'),
        ),
    ]
