# Generated by Django 2.2.10 on 2020-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200611_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=20, verbose_name='provider'),
        ),
    ]
