# Generated by Django 2.2.10 on 2020-06-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200623_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=250, verbose_name='provider'),
        ),
    ]
