# Generated by Django 2.2.10 on 2020-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200623_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='provider'),
        ),
    ]
