# Generated by Django 2.2.10 on 2020-08-17 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200623_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default='2000-01-01', verbose_name=datetime.datetime.now),
        ),
    ]
