# Generated by Django 2.2.10 on 2020-08-17 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200817_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.DateTimeField(default='2000-01-01', verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
