# Generated by Django 2.2.10 on 2020-07-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact_time',
        ),
    ]
