# Generated by Django 2.2.10 on 2020-07-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_contact_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='body',
            new_name='details',
        ),
    ]
